name: backend-tests-workflow

on:
  push:
    branches: [staging]
jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto server and run tests
        run: cd backend && npm i && npm test
