services:
  backend:
    image: hyna42/app-tgc-v2-backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:4000'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 1s
      timeout: 2s
      retries: 100
  frontend:
    image: hyna42/app-tgc-v2-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --request GET --url 'http://localhost:5173' || exit 1"
      interval: 1s
      timeout: 2s
      retries: 100
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data # Permet de sauvegarder les données
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 2s
      retries: 100
  adminer:
    image: adminer
    depends_on:
      db:
        condition: service_healthy
  img:
    image: hyna42/app-tgc-v2-img
    healthcheck:
      test: "curl --fail --request GET --url 'http://localhost:4000' || exit 1"
      interval: 1s
      timeout: 2s
      retries: 100
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_healthy
    volumes:
      - /apps/tgc-v2/staging/img/uploads:/app/uploads
  api_gateway:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
      img:
        condition: service_healthy
    ports:
      - ${GATEWAY_PORT}:80
volumes:
  postgres_data: