name: frontend-tests-workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - staging

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto client and run tests
        run: cd frontend && npm i && npm test
  docker:
    needs: test-client
    # if: github.ref == 'refs/heads/staging'
    if: github.event_name == 'pull_request' && github.base_ref == 'staging'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend image to DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-tgc-v2-frontend:latest

#hellotest