name: full-ci-workflow

on:
  push:
    branches:
      - staging
      - develop

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto client and run tests
        run: cd frontend && npm i && npm test
  docker-frontend:
    needs: test-client
    # if: github.event_name == 'pull_request' && github.base_ref == 'staging'
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend image to DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          # context: "{{defaultContext}}:frontend"
          context: frontend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-tgc-v2-frontend:latest
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto server and run tests
        run: cd backend && npm i && npm test
  docker-backend:
    needs: test-server
    # if: github.event_name == 'pull_request' && github.base_ref == 'staging'
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend image to DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          # context: "{{defaultContext}}:backend"
          context: backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-tgc-v2-backend:latest
